# print('你好，浪晋学院')
# print(2333)
# print(2.333)
# print(True,False)
# print(())
# print({})
# print([])
# print(None)
# print(False and False)
# print(False and True)
# print(True or False)
# print(16%5)
# a = float(input('请输入数字：'))
# b = float(input('请输入数字2：'))
# print(a + b)
a = input('请输入文章内容：')
print('总输入字数：',len(a))